python -m pip install --upgrade pip==24.2
python -m pip install --upgrade cloudpickle==3.0.0
python -m pip install --upgrade contourpy==1.3.0
python -m pip install --upgrade cycler==0.12.1
python -m pip install --upgrade Farama-Notifications==0.0.4
python -m pip install --upgrade filelock==3.16.1
python -m pip install --upgrade fonttools==4.54.1
python -m pip install --upgrade fsspec==2024.9.0
python -m pip install --upgrade imageio==2.35.1
python -m pip install --upgrade Jinja2==3.1.4
python -m pip install --upgrade kiwisolver==1.4.7
python -m pip install --upgrade lazy_loader==0.4
python -m pip install --upgrade MarkupSafe==2.1.5
python -m pip install --upgrade matplotlib==3.9.2
python -m pip install --upgrade mpmath==1.3.0
python -m pip install --upgrade networkx==3.3
python -m pip install --upgrade nvidia-cublas-cu12==12.1.3.1
python -m pip install --upgrade nvidia-cuda-cupti-cu12==12.1.105
python -m pip install --upgrade nvidia-cuda-nvrtc-cu12==12.1.105
python -m pip install --upgrade nvidia-cuda-runtime-cu12==12.1.105
python -m pip install --upgrade nvidia-cudnn-cu12==9.1.0.70
python -m pip install --upgrade nvidia-cufft-cu12==11.0.2.54
python -m pip install --upgrade nvidia-curand-cu12==10.3.2.106
python -m pip install --upgrade nvidia-cusolver-cu12==11.4.5.107
python -m pip install --upgrade nvidia-cusparse-cu12==12.1.0.106
python -m pip install --upgrade nvidia-nccl-cu12==2.20.5
python -m pip install --upgrade nvidia-nvjitlink-cu12==12.6.77
python -m pip install --upgrade nvidia-nvtx-cu12==12.1.105
python -m pip install --upgrade opencv-contrib-python==4.10.0.84
python -m pip install --upgrade packaging==24.1
python -m pip install --upgrade pillow==10.4.0
python -m pip install --upgrade psutil==6.0.0
python -m pip install --upgrade pyparsing==3.1.4
python -m pip install --upgrade python-dateutil==2.9.0.post0
python -m pip install --upgrade pytz==2024.2
python -m pip install --upgrade setuptools==72.1.0
python -m pip install --upgrade six==1.16.0
python -m pip install --upgrade sympy==1.13.3
python -m pip install --upgrade tifffile==2024.9.20
python -m pip install --upgrade triton==3.0.0
python -m pip install --upgrade typing_extensions==4.12.2
python -m pip install --upgrade tzdata==2024.2
python -m pip install --upgrade wheel==0.44.0
python -m pip install --upgrade stable_baselines3==2.3.2
python -m pip install --upgrade gymnasium==0.29.1
python -m pip install --upgrade numpy==2.1.1
python -m pip install --upgrade pandas==2.2.3
python -m pip install --upgrade scikit-image==0.24.0
python -m pip install --upgrade scipy==1.14.1
python -m pip install --upgrade torch==2.4.1
python -m pip install --upgrade backports.ssl_match_hostname==3.7.0.1
python -m pip install --upgrade tornado==4.5.3
python -m pip install --upgrade msgpack-python==0.5.6
python -m pip install --upgrade msgpack-rpc-python==0.4.1
python -m pip install --upgrade airsim==1.8.1
